### ISSUE TITLE
Not type-safe with a typescript config for Vite 4.1.1

### ISSUE THREAD

**Issue by nicolasalt** [FatehAK/vite-plugin-image-optimizer#13]
### Describe the Bug

I have to use `ViteImageOptimizer() as PluginOption` as a workaround, otherwise VSCode complains (no issues with the actual build): 

![image](https://user-images.githubusercontent.com/1146358/221996855-74d0da95-d894-4293-9f91-245b49cd170d.png)

Full config:

```
import react from '@vitejs/plugin-react';
import { ViteImageOptimizer } from 'vite-plugin-image-optimizer';
import { defineConfig, PluginOption } from 'vite';

export default defineConfig({
  plugins: [react(), ViteImageOptimizer() as PluginOption],
});

```

### Steps to reproduce

 - Use a Typescript Vite config "vite.config.ts" with Vite 4.1.1.

### System Info

```shell
-
```

### Used Package Manager

yarn

### Validations

- [X] Read the [docs](https://github.com/FatehAK/vite-plugin-image-optimizer#readme).
- [X] Check that there isn't [already an issue](https://github.com/FatehAK/vite-plugin-image-optimizer/issues) that reports the same bug to avoid creating a duplicate.

**Comment by FatehAK** [comment]
Just published a new version with TS typings. Please update the package to `v1.1.0` and see if that fixes it. Thanks!

**Comment by nicolasalt** [comment]
Thanks a lot for the quick fix!

And thanks for this plugin, in my app it worked right away without any additional tuning and reduced the total images size by more than 50% without significant quality drop.
