### ISSUE TITLE
Totals for the stats

### ISSUE THREAD

**Issue by dflock** [FatehAK/vite-plugin-image-optimizer#18]
### Describe the feature you'd like to request

It would be nice if the stats also printed out a total at the bottom: total % and total Kb/Mb saved.

### Describe the solution you'd like

If this was another config flag, maybe `logStatsTotal`, that would also be fine - although I don't think that's nescessary.

### Additional context

Thanks very much for this awesome vite plugin - it works great!

### Validations

- [X] Read the [docs](https://github.com/FatehAK/vite-plugin-image-optimizer#readme).
- [X] Check that there isn't [already an issue](https://github.com/FatehAK/vite-plugin-image-optimizer/issues) that requests the same feature to avoid creating a duplicate.

**Comment by FatehAK** [comment]
Thank you for the cool idea, @dflock! I'll definitely look into it. Expect to hear back from me next week, although I might be a bit busy for the next few days.

**Comment by FatehAK** [comment]
This feature is now live folks! Please update to v1.1.5

A sample screenshot
![Screen Shot 2023-05-25 at 12 58 18 AM](https://github.com/FatehAK/vite-plugin-image-optimizer/assets/34565559/9c738f60-f985-4e76-8398-56955bf139f2)
