### ISSUE TITLE
"Caching" - Support

### ISSUE THREAD

**Issue by niklas-wortmann** [FatehAK/vite-plugin-image-optimizer#24]
### Describe the feature you'd like to request

I'd like to be able to not run the optimization on images that have already been optimized before.

### Describe the solution you'd like

Haven't looked in detail in the code yet so there might be a better approach, but I'd suggest adding 2 configuration parameters, "cache" (boolean) and "cachePath" (string). If cache is set to true, we save a file in the cachePath which is basically a list of the image path + name and it's related hash. This way we could check if an already cached image was changed if not, there is no need to rebuild it

### Additional context

We are using this plugin at JetBrains right now to rebuild our blog. As you can imagine we have plenty of pictures and graphics and stuff, so optimizing the image takes roughly 6 minutes right now, every single time

### Validations

- [X] Read the [docs](https://github.com/FatehAK/vite-plugin-image-optimizer#readme).
- [X] Check that there isn't [already an issue](https://github.com/FatehAK/vite-plugin-image-optimizer/issues) that requests the same feature to avoid creating a duplicate.

**Comment by FatehAK** [comment]
Hello, @niklas-wortmann and @pauleveritt, I apologize for not getting back earlier. I am amazed that JetBrains is employing my plugin! Let me address your questions:

a) It was in my backlog, but at that time, I didn't have the requirement for extensive image processing. Ideally, it would work similarly to how Prettier and ESLint cache functions, I believe.

b) Currently, I'm quite busy with work and won't be able to devote time to build this feature. However, I'm always happy to welcome a PR if you folks are open to contributing it.

**Comment by niklas-wortmann** [comment]
Great we are more than happy to file a pr for this. I will look into Prettier and ESLint caching and see what we can do

**Comment by maartenba** [comment]
PR is in! Happy to make any changes you see fit.

**Comment by pauleveritt** [comment]
Thanks a bunch @FatehAK

**Comment by FatehAK** [comment]
Thank you for the PR and coordinating this. I hope this saves you folks a good chunk of time and enables swift deployments for your blog 😄

**Comment by maartenba** [comment]
We managed to shave off 4 minutes, which is quite nice 🙂 Thanks for the swift review!

**Comment by FatehAK** [comment]
That's Awesome 😀
