### ISSUE TITLE
Not working in Laravel 10

### ISSUE THREAD

**Issue by brilik** [FatehAK/vite-plugin-image-optimizer#26]
### Describe the Bug

I'm can't run your plugin. I'm not see stats showing in console after build. I'm not have optimized images.
<img width="660" alt="Снимок экрана 2023-08-20 в 01 34 16" src="https://github.com/FatehAK/vite-plugin-image-optimizer/assets/27772771/9397ed20-766b-4846-abd0-4852636d723d">
<img width="506" alt="Снимок экрана 2023-08-20 в 01 35 54" src="https://github.com/FatehAK/vite-plugin-image-optimizer/assets/27772771/89b882fa-de5f-48c4-b2f0-59ec1cbdc899">
<img width="599" alt="Снимок экрана 2023-08-20 в 01 36 32" src="https://github.com/FatehAK/vite-plugin-image-optimizer/assets/27772771/d74d91f3-fe91-4309-bfdf-8eb3eb019663">

### Steps to reproduce

1. I have image by path: `./resources/img/logo.png`
2. I'm run command: `npm run build`
3. I'll hope to see my image by path `./public/build/assets/img/logo.png`

### System Info

```shell
No error info. I'm not see stats showing in console after build
```

### Used Package Manager

npm

### Validations

- [X] Read the [docs](https://github.com/FatehAK/vite-plugin-image-optimizer#readme).
- [X] Check that there isn't [already an issue](https://github.com/FatehAK/vite-plugin-image-optimizer/issues) that reports the same bug to avoid creating a duplicate.

**Comment by brilik** [comment]
You should add to Readme.md this code in app.js:
```
import.meta.glob([
    '../img/**',
])
```
It's resolve my problem

**Comment by brilik** [comment]
You should add to Readme.md this code in app.js:

import.meta.glob([
    '../img/**',
])
It's resolve my problem

**Comment by Airhune** [comment]
I have the same problem, the plugin doesn't run and I don't know why it could be. 
Have you added that in resources/js/app.js?

**Comment by brilik** [comment]
> I have the same problem, the plugin doesn't run and I don't know why it could be. Have you added that in resources/js/app.js?

Yes, I'm put to resources/js/app.js:
```
import.meta.glob([
    '../img/**',
])
```
and u should update folder name.
