### ISSUE TITLE
Errors hidden behind "failed optimization" message

### ISSUE THREAD

**Issue by mfjordvald** [FatehAK/vite-plugin-image-optimizer#4]
Currently when an error happens it's hidden behind a generic failed message. This makes it difficult to debug what is going wrong. Might make sense to collect errors and present them at the end of the build process.

https://github.com/FatehAK/vite-plugin-image-optimizer/blob/main/src/index.js#L54

**Comment by FatehAK** [comment]
Good idea! Will look into it

**Comment by FatehAK** [comment]
This has been implemented with version 1.0.5. 

A sample screenshot:
![Screen Shot 2022-12-31 at 6 05 37 PM](https://user-images.githubusercontent.com/34565559/210137158-37a3869e-d775-444d-934f-6e8ba0c2dbba.png)
